# Generated by Django 5.1.3 on 2024-11-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment',
            field=models.CharField(default='оплачено', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.CharField(default='2200', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.day'),
        ),
        migrations.AddField(
            model_name='client',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.month'),
        ),
        migrations.AddField(
            model_name='client',
            name='sport_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.sportcategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.year'),
        ),
    ]
