# Generated by Django 5.1.3 on 2024-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_day_month_sportcategory_trainer_year_client_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='primer@gmail.com', max_length=100),
        ),
    ]
