# Generated by Django 5.1.3 on 2024-11-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='day',
            field=models.CharField(choices=[('1', 'Бокс'), ('2', 'Футбол'), ('3', 'Теннис'), ('4', 'Плавание'), ('5', 'Бе'), ('6', 'Бе'), ('7', 'Бе'), ('Август', 'Бе'), ('Сентябрь', 'Бе'), ('Октябрь', 'Бе'), ('Ноябрь', 'Бе'), ('Декабрь', 'Бе')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='month',
            field=models.CharField(choices=[('Январь', 'Бокс'), ('Февраль', 'Футбол'), ('Март', 'Теннис'), ('Апрель', 'Плавание'), ('Май', 'Бе'), ('Июнь', 'Бе'), ('Июль', 'Бе'), ('Август', 'Бе'), ('Сентябрь', 'Бе'), ('Октябрь', 'Бе'), ('Ноябрь', 'Бе'), ('Декабрь', 'Бе')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sport_category',
            field=models.CharField(choices=[('Бокс', 'Бокс'), ('Футбол', 'Футбол'), ('Теннис', 'Теннис'), ('Плавание', 'Плавание'), ('Бег', 'Бег')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='trainer',
            field=models.CharField(choices=[('Мирлан', 'Бокс'), ('Ермек', 'Футбол'), ('Эрнис', 'Теннис'), ('Арсен', 'Плавание'), ('Дияр', 'Бег')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='year',
            field=models.CharField(choices=[('2020', 'Бокс'), ('2021', 'Футбол'), ('2022', 'Теннис'), ('2023', 'Плавание'), ('2024', 'Бе'), ('2025', 'Бе'), ('2026', 'Бе')], max_length=100, null=True),
        ),
        migrations.RenameField(
            model_name='salespipelinestage',
            old_name='client',
            new_name='clients',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='SportCategory',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
